PREFIX issda:<http://example.org/>

SELECT ?meterNum ?occupier ?numberOfPersons
WHERE {?meterNum issda:associatedOccupier ?occupier . ?occupier issda:numberOfPersons ?numberOfPersons}

SELECT ?occupier ?yearlyIncome
WHERE {?occupier issda:yearlyIncome ?yearlyIncome . ?occupier issda:owns ?owns . FILTER (?yearlyIncome > 75000)}

SELECT ?meterNum ?timeWindowEnd SUM(?consumption)
WHERE {(?meterNum issda:consumption ?consumption , ?timestamp)}
GROUP BY ?meterNum ?timeWindowEnd
TIMEWINDOW (3h, 1h)
